apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: {{ .Values.app }}
    version: {{ .Values.version }}
  ports:
    - name: http-web
      port: 80
      targetPort: {{ .Values.port | default 80 }}